name: Build and Deploy Documentation

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'      # Prevent re-triggering the workflow on docs update
  workflow_dispatch:   # Allows manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false   # Disable to use custom token if needed
          fetch-depth: 0               # Full history for accurate git info

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'        # Specify your desired Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run Documentation Build Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          chmod +x docs/build_docs.sh
          docs/build_docs.sh

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add docs
          git commit -m "Automated docs build [skip ci]" || exit 0
          git push origin HEAD:main
