name: Build and Deploy Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Set executable permissions for build_docs.sh
        run: chmod +x ./docs/build_docs.sh

      - name: Build documentation
        run: ./docs/build_docs.sh

      - name: Add only necessary build artifacts
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          # Add only necessary files (index.html, _static/, etc.)
          git add -f docs/index.html docs/_static/ docs/_sources/ docs/libs/
          git commit -m "Update documentation" || echo "No changes to commit"
          git push "https://${GH_TOKEN}@github.com/hc-sc-ocdo-bdpd/file-processing-guide.git" main
